---
name: Build & Verify Terraform Module
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  Terraform-Lint:
    runs-on: arc-runner-scale-set-s3-minio-config
    container:
      image: ghcr.io/terraform-linters/tflint:v0.50.0
    environment: k8s
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - run: |
          tflint --recursive
