---
name: Validate and Release Terraform Module
on:
  workflow_dispatch:
    inputs:
      release-tag:
        required: true
        type: string
      release-message:
        required: true
        type: string

jobs:
  validate-terraform:
    name: Valdiate
    uses: stuttgart-things/stuttgart-things/.github/workflows/validate-terraform.yaml@main  
    with:
      environment-name: k8s
      runs-on: ghr-s3-minio-config-sthings-cicd
      terraform-version: 1.6
      tflint-version: "v0.50.0"
      continue-error: false

  release-terraform:
    name: Release
    needs: validate-terraform
    uses: stuttgart-things/stuttgart-things/.github/workflows/release-terraform.yaml@main  
    with:
      module-name: s3-minio-config
      tag-name: "${{ github.event.inputs.release-tag }}"
      release-message: "${{ github.event.inputs.release-message }}"
      environment-name: k8s
      runs-on: ghr-s3-minio-config-sthings-cicd
      continue-error: false
