---
name: Terraform
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  validate-terraform:
    name: Valdiate
    uses: stuttgart-things/stuttgart-things/.github/workflows/validate-terraform.yaml@main  
    with:
      environment-name: k8s
      runs-on: arc-runner-scale-set-s3-minio-config
      terraform-version: 1.6
      tflint-version: "v0.50.0"
      continue-error: false
