---
name: Terraform
on:
  push:
    branches:
      - main
      - feature/*
      - review/*
      - fix/*
  pull_request:
    types: [opened, reopened]

jobs:
  validate-terraform:
    name: Valdiate
    uses: stuttgart-things/stuttgart-things/.github/workflows/validate-terraform.yaml@main
    with:
      environment-name: k8s
      runs-on: ghr-s3-minio-config-sthings-cicd
      terraform-version: 1.6
      tflint-version: "v0.50.0"
      continue-error: false
